
service: projectzoro1

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::*'
  region: us-west-2
functions:
  lambdapy:
    handler: lambdapy.handler
    events:
      - http:
          path: /create
          method: get
plugins:
  - serverless-python-requirements
