
service: project122

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  role: arn:aws:iam::319675664350:role/admin
  region: us-west-2
functions:
  lambdapy:
    handler: lambdapy.handler
    events:
      - http:
          path: /create
          method: get
plugins:
  - serverless-python-requirements
