service: {{ .values.name}}
frameworkVersion: '2'

provider:
  name: aws
  runtime: {{ .Values.runtime }}
  region: {{ .Values.region }}
  iamRoleStatements:
    {{- include "testchart.list-resources" .| indent 10 }}
functions:
  {{ .Values.handler }}:
    handler: {{ .Values.handler }}.handler
plugins:
  - serverless-python-requirements
