---
  - name: create serverless template
    hosts: localhost
    connection: local
    vars_files:
      - values.yml
    tasks:
      - name: Create the Jinja2 based template
        template: src=./deploy.j2 dest=../serverless.yml
